name: "Publish container templates"
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dev Container Publish
        uses: devcontainers/action@v1.4.0
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
